### ISSUE TITLE
How to add to list? Artificy - image generation service for free

### ISSUE THREAD

**Issue by x-name** [questianon/sdupdates#2]
How I can add information about service?

* Service of free image generation: [Artificy.com](https://artificy.com/)
	* Free for personal use
	* We use all most fresh, models for example
	* Different aspect ratios, predefined styles
	* Fast and simple interface
	* Social network features: make & share!
	* Work in progress every day

**Comment by questianon** [comment]
Just doing it like this is good enough. Thanks for the link, I'll add it later
