### ISSUE TITLE
Activate python virtual environment before installing packages with pip

### ISSUE THREAD

**Issue by ekce** [questianon/sdupdates#5]
At the bottom of the 10/21 - 10/25 section it gives instructions for updating. These instructions should activate the python virtual environment before calling pip otherwise the packages will be installed globally. This can cause conflicts with package managers on Linux.
Instead you should activate the python virtual environment first, like in https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Xformers

**Comment by questianon** [comment]
Edited, thanks for pointing this out. If the instructions are still wrong, just send another issue my way and I'll fix it
